[package]
name = "araki"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
directories = "6.0.0"
git2 = { version = "0.20.2", features = ["https", "ssh"] }
sysinfo = "0.37.2"
