[project]
authors = ["sophia <scastellarin@quansight.com>"]
channels = ["conda-forge"]
description = "akari demo - manage and share environments"
name = "akari-one"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"

[dependencies]
rust = ">=1.90.0,<1.91"
openssl = ">=3.5.4,<4"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.11.0,<2"
