[workspace]
authors = ["sophia <scastellarin@quansight.com>"]
channels = ["conda-forge"]
description = "araki demo - manage and share environments"
name = "araki"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"
fmt = "cargo fmt --all"

[dependencies]
rust = ">=1.90.0,<1.91"
openssl = ">=3.5.4,<4"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.11.0,<2"
